#!/bin/sh

## Directories used ###############################################################################
sugarCandyBackgrounds="/usr/share/sddm/themes/sugar-candy/Backgrounds"
walColorsDir=${HOME}"/.cache/wal/colors"
userThemeFile="/usr/share/sddm/themes/sugar-candy/theme.conf.user"
###################################################################################################

## Safety checks ##################################################################################

for dir in \
        "$sugarCandyBackgrounds"
do
    echo "$dir"
    if ! [ -d "$dir" ]; then
        exit 1;
    fi
done


###################################################################################################


## Arguments ######################################################################################
numArgs=$#
lastArg="${!numArgs}"
shouldGenerateLightTheme=false
formPosition="left"
fallbackWallpaper=`awk -F'file://' '{print $2}' <<< $($HOME/.config/variety/scripts/get_wallpaper)`
imagePath="$fallbackWallpaper"

# VALID_ARGS=$(getopt -o abg:d: --long alpha,beta,gamma:,delta: -- "$@")
VALID_ARGS=$(getopt -o lRi: --long light,right,image: -- "$@")
if [[ $? -ne 0 ]]; then
    exit 1;
fi

eval set -- "$VALID_ARGS"
while [ : ]; do
  case "$1" in
    -l | --light)
        echo "Light theme will be generated"
        shouldGenerateLightTheme=true
        shift
        ;;
    -R | --right)
        echo "Form position will be 'right'"
        formPosition="right"
        shift
        ;;
    -i | --image)
        echo "Image is '$2'"
        imagePath="$2"
        shift 2
        ;;
    --) shift;
        break
        ;;
  esac
done
###################################################################################################


## Info from args #################################################################################
imageName="$(basename -- "$imagePath")"
backgroundPath="$sugarCandyBackgrounds/$imageName"
###################################################################################################


## Moving image to root ###########################################################################
sudo cp -uv "$imagePath" "$sugarCandyBackgrounds"
###################################################################################################


## Setting wal colors #############################################################################
if [ "$shouldGenerateLightTheme" = true ] ;
then
    wal -i "$imagePath" -l --backend schemer2 &
else
    wal -i "$imagePath" --backend schemer2 &
fi

wait "$!"
###################################################################################################


## Get hex colors from Wal cache ##################################################################
index=1
for line in `cat $walColorsDir`
do
    eval "color$index=$line"
    index=$((index+1));
done
MainColor="$color8"
BackgroundColor="$color1"
AccentColor="$color4"
###################################################################################################


## Set sugar-candy sddm theme background and colors ###############################################
echo "\
[General]
Background=\"$backgroundPath\"
MainColor=\"$MainColor\"
AccentColor=\"$AccentColor\"
BackgroundColor=\"$BackgroundColor\"
FormPosition=\"$formPosition\"
" | sudo tee "$userThemeFile"
###################################################################################################


## Revert wal changes #############################################################################
variety -n
###################################################################################################


## Test the sddm theme ############################################################################
sddm-greeter --test-mode --theme /usr/share/sddm/themes/sugar-candy
###################################################################################################
