#!/bin/sh

card=$1

cardDir="/proc/asound/card$card/"

GREEN="\033[1;32m"
NOCOLOR="\033[0m"
RED='\033[0;31m'

if [ -d "$cardDir" ]; then
    echo
else
    echo -e "${RED}Card not found, here is audio devices playback info"
    echo
    audioDevicesPlaybackInfo
    exit 0
fi

codecFile="$cardDir/codec#0"

if [ -f "$codecFile" ]; then
    cat "$codecFile"
    exit 0
fi

streamFile="$cardDir/stream0"

if [ -f "$streamFile" ]; then
    cat "$streamFile"
    exit 0
fi

echo -e "${RED}Cannot find audio device info, ${GREEN}here is audio devices playback info ${NOCOLOR}"
echo
audioDevicesPlaybackInfo
exit 0
